### ISSUE TITLE
Question: what load balancing algorithm does session_sticky use?

### ISSUE THREAD

**Issue by elie222** [ramezrafla/meteor-deployment#2]
What load balancing algorithm does `session_sticky` use in the `nginx.conf` file?

**Comment by ramezrafla** [comment]
It's all in the tengine docs (see link in readme). Sticky session is cookie-based and the load balancing is round robin.

**Comment by elie222** [comment]
Thanks. I searched the docs but didn't see the round Robin bit.

Any idea if it's possible to use least connections with sticky sessions?
That seems like the best load balancing algo for meteor apps.

**Comment by ramezrafla** [comment]
Checking .. how do you do it now? MUP does not handle webserver side.

**Comment by ramezrafla** [comment]
Based on my reading of http://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_with_ip_hash it's either session persistence or least conn. Meteor session persistence seems like a no-brainer, but haven't tested switching to least conn. I'll try later and report here.

**Comment by elie222** [comment]
Least connections isn't a good solution for meteor. You want sticky
sessions which is why you use iphash with nginx. Only the paid version of
nginx allows sticky sessions with least connections.

**Comment by ramezrafla** [comment]
Agreed, so we did some research. Can't find where sticky sessions and least conn coexist in nginx.

In fact, if you read: http://stackoverflow.com/questions/31797593/nginx-least-connections-with-sticky-sessions, it will explain that it does not make sense. Here is why: 

Once you have a server assigned to you, you will always get that server. If you don't, then least conn algorithm will chose for you GIVEN THE LOAD AT THAT TIME ONLY! i.e. it will distribute the load as evenly as it can based on current usage. When you come back later, you will get the same server, and the load will likely become unbalanced as the algorithm of least conn won't kick in as your session is already present. So least conn only worked the first time you connected. Not very useful.

**Comment by elie222** [comment]
I'm pretty sure nginx plus does allow for it.

And yeah, it's only helpful the first time. I assume a login 3 months
before won't keep you on that same server either, but things get reset
every so often when the user leaves the site or after a given timeout.

**Comment by elie222** [comment]
You also have exactly the same issues with round Robin least connections.

Nginx uses ip_hash to do sticky sessions (which isn't round robin)

**Comment by ramezrafla** [comment]
@elie222, if this issue is addressed, can we close this? tengine with sticky session is used by a couple of the world's largest ecommerce sites. We'll keep watching our install but so far, load is on average well balanced.

Also, when you go through a server restart due to updates, users get reshuffled any way.

**Comment by elie222** [comment]
Yes this can be closed.
