### ISSUE TITLE
Feature Request: Automate more

### ISSUE THREAD

**Issue by elie222** [ramezrafla/meteor-deployment#3]
Hi,

The first thing I notice when using this package is that a lot of the things have to be done manually. One of the advantages of my current MUPX setup is that everything is done automatically. I don't have to manually install node and pm2 on the server. Nor do I have to start anything manually on the server. This will be a hassle as I'm often putting up and down 10s of servers at a time.

I use DigitalOcean for deployments so I'd probably set up an image once with any prerequisites installed which would get around this issue.

**Comment by ramezrafla** [comment]
We use DO too. You still have to setup your server regardless (e.g. ssh, webserver etc.) So yes, an image is the way to go. 

If you were using mup, you would need separate json file for each server. So mup is not scalable. Here you have the basis to customize your scripts. 

In fact, if you are really automating 10s of servers, you are likely to use the API of DO. Now it's really scalable!

**Comment by elie222** [comment]
Ok. That's good to know. You don't need multiple files with mup. You can
stick 100 servers all in the same file, and have different env vars for
each.

**Comment by ramezrafla** [comment]
I'll keep this open as a setup script to run on a new VM would be helpful. It's on our todo as we add more machines. We'll be doing this shortly.

**Comment by zeroasterisk** [comment]
I'm also interested in this setup.  I agree PM2 is wonderful, and nginx in front is awesome.  Tengine is promising. 

What I'd like to see is a dockerized install of all of this, which was "done".  
Mount a meteor bundle and config and go.
We are using kubernetes to manage containers, and Galaxy is using ECS - docker is a very reasonable way to configure and deploy services.

Do you have plans to move in that direction?

**Comment by jlichti** [comment]
Also interested - especially in the Tengine setup. We're currently using nginx with ip_hash and occasionally servers max out so the check module would be helpful. If you have it already created would you mind sharing the modules you use when configuring and building Tengine?

Thanks for sharing!

**Comment by ramezrafla** [comment]
@zeroasterisk sorry for delay -- didn't see notifications go by. We are not using Docker as our VMs are customized for Meteor. There is a forum thread on the topic though.

@jlichti Tengine comes with sticky_session built-in out of the box. Check out the conf file in the repo.
